# Input files
# Sequences
samples: sample_sheets/sqmp-samples.tsv
# Kaiju database files
db: /gpfs/fs3c/aafc/aafc_shp/lal000/taxonomic_profiling_pipeline/database_kaiju_nr_euk/kaiju_db_nr_euk.fmi
NODES_DMP: /gpfs/fs3c/aafc/aafc_shp/lal000/taxonomic_profiling_pipeline/database_kaiju_nr_euk/nodes.dmp
NAMES_DMP: /gpfs/fs3c/aafc/aafc_shp/lal000/taxonomic_profiling_pipeline/database_kaiju_nr_euk/names.dmp

# Threads
THREADS: 8

# Flags for specifying whether you want to keep certain output products
# The fastp processed read files
keep_fastp: true
# The bowtie2 processed read files
keep_bowtie2: true
# The individual fastqc reports
keep_fastqc: true
